package com.trelloiii.simplereapitinglib;

import com.trelloiii.simplereapitinglib.instance.InstanceType;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

@Target({ElementType.TYPE})
@Retention(RetentionPolicy.RUNTIME)
public @interface AutoGenerated {
    String instanceType() default InstanceType.SINGLE;
}
