package com.trelloiii.jigul.scanner.test;

import com.trelloiii.jigul.ioc.AutoGenerated;
import com.trelloiii.jigul.ioc.instance.InstanceType;

@AutoGenerated(instanceType = InstanceType.MULTI)
public class Person {
    private String name="DEFAULT";
    private String surname="DEFAULT";


    public Person(String name, String surname) {
        this.name = name;
        this.surname = surname;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    public Person() {
        System.out.println("INSTANCE OF PERSON");
    }

    public String getName() {
        return name;
    }

    public void voice(){
        System.out.println("my name is: "+this.name);
    }
}
