package com.trelloiii.jigul.ioc.instance;

import com.trelloiii.jigul.ioc.AutoGenerated;
import com.trelloiii.jigul.ioc.Bean;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.util.HashMap;
import java.util.List;

public class ObjectInstance {

    private SingleInstance singleInstance;
    private static FieldInstance fieldInstance;
    private HashMap<Class,Object> singleInstances;
    private static ObjectInstance objectInstance;
    private Object userConfiguration;
    private HashMap<Class<?>,Method> beanClasses;
    private ObjectInstance(List<Class<?>> classes,List<Method> methods,Object userConfiguration) {
        singleInstance=SingleInstance.build();
        beanClasses=new HashMap<>();
        this.userConfiguration=userConfiguration;
        checkInstanceType(classes);
        checkBean(methods);
        singleInstances=singleInstance.getSingleObjects();
    }
    public static ObjectInstance builder(List<Class<?>> classes,List<Method> methods,Object userConfiguration){
        if(objectInstance==null){
            objectInstance=new ObjectInstance(classes,methods,userConfiguration);
            fieldInstance=new FieldInstance(objectInstance);
            fieldInstance.injectToSingleInstances();
        }

        return objectInstance;
    }

    public Object getInstance(Class clazz){
        if(singleInstances.containsKey(clazz)){
            return singleInstances.get(clazz);
        }
        else{
            if(checkMultiInstance(clazz)){
                //new instance
                return multiInstance(clazz);
            }
            else if(beanClasses.containsKey(clazz)){
                return multiInstance(beanClasses.get(clazz));
            }
            else{
                throw new IllegalArgumentException("Class "+clazz.getName()+" is not marked @AutoGenerated");
            }
        }
    }
    public HashMap<Class, Object> getSingleInstances() {
        return singleInstances;
    }

    private boolean checkMultiInstance(Class clazz){
        AutoGenerated autoGenerated=(AutoGenerated) clazz.getAnnotation(AutoGenerated.class);
        return !(autoGenerated ==null);
    }
    private void checkInstanceType(List<Class<?>> classes){
        for(Class clazz:classes){
            AutoGenerated autoGenerated=(AutoGenerated) clazz.getAnnotation(AutoGenerated.class);
            if(autoGenerated.instanceType().equals(InstanceType.SINGLE)){
                singleInstance(clazz);
            }
            else if(autoGenerated.instanceType().equals(InstanceType.MULTI)){
              //  multiInstance(clazz);
            }
            else{
                throw new IllegalArgumentException("Wrong InstanceTypeValue in class: "+clazz.getName());
            }
        }
    }

    private Object multiInstance(Class clazz) {
        System.out.println("class "+clazz.getName()+" is multi instance");
        try {
            Object returned=clazz.newInstance();
            fieldInstance.fieldInstance(returned,clazz);
            return returned;

        } catch (Exception e){
            e.printStackTrace();
            return null;
        }
    }
    private Object multiInstance(Method m){
        try {
            Object returned=m.invoke(this.userConfiguration);
            fieldInstance.fieldInstance(returned,m.getReturnType());
            return returned;
        } catch (IllegalAccessException e) {
            e.printStackTrace();
            return null;
        } catch (InvocationTargetException e) {
            e.printStackTrace();
            return null;
        }
    }

    private void singleInstance(Class clazz) {
        System.out.println("class "+clazz.getName()+" is single instance");
        singleInstance.instance(clazz);
    }

    private void checkBean(List<Method> methods){
        for(Method method:methods){
            Bean bean=method.getAnnotation(Bean.class);
            beanClasses.put(method.getReturnType(),method);
            if(bean.instanceType().equals(InstanceType.SINGLE)){
                try {
                    Object buildedBean=method.invoke(this.userConfiguration);
                    singleInstance.instance(buildedBean);
                } catch (IllegalAccessException e) {
                    e.printStackTrace();
                } catch (InvocationTargetException e) {
                    e.printStackTrace();
                }
            }
            else if(bean.instanceType().equals(InstanceType.MULTI)){
                //TODO bean multi instance????????
            }
            else {
                throw new IllegalArgumentException("Wrong InstanceTypeValue in bean "+method.getName());
            }

        }
    }


}
