package com.trelloiii.simplereapitinglib.scanner.test;

import com.trelloiii.simplereapitinglib.ioc.AutoGenerated;
import com.trelloiii.simplereapitinglib.Configuration;
import com.trelloiii.simplereapitinglib.ioc.Injectable;
import com.trelloiii.simplereapitinglib.ioc.instance.InstanceType;
import com.trelloiii.simplereapitinglib.ioc.pool.ObjectPool;

@AutoGenerated(instanceType = InstanceType.MULTI)
public class Car {
    private String mark;
    private String color;
    @Injectable
    private Person driver;
    private Person passenger;

    public Car(String mark, String color) {
        this.mark = mark;
        this.color = color;
    }

    public String getMark() {
        return mark;
    }

    public Car() {
        this.mark="Mercedes";
        this.color="Black";
    }

    public void setPassenger(Person passenger) {
        this.passenger = passenger;
    }

    public Person getDriver() {
        return driver;
    }

    public void beep(){
        System.out.println(this.mark+" : "+this.color+", driver is:"+this.driver.getName()+",passenger is: "+this.passenger.getName());
    }

    public void pickUpPassenger(){
        try {
            ObjectPool pool=new ObjectPool(Configuration.getConfiguration());
            Person passenger=pool.getPooledObject(Person.class);
            passenger.setName("KOCK");
            setPassenger(passenger);
        } catch (InstantiationException e) {
            e.printStackTrace();
        }
    }
}
