package com.trelloiii.simplereapitinglib.scanner;

import com.trelloiii.simplereapitinglib.AutoGenerated;
import com.trelloiii.simplereapitinglib.Controller;
import com.trelloiii.simplereapitinglib.Injectable;

import java.lang.annotation.Annotation;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.util.*;

public class AnnotationScanner {


    public AnnotationScanner() {
    }

    public List<Class<?>> scanAutoGenerated(List<Class<?>> classes){
        List<Class<?>> autoGeneratedClasses=new ArrayList<>();
//        List<Field> injectableFields=new ArrayList<>();
//        Map<List<Class<?>>,List<Field>> classAndFields=new HashMap<>();
        for(Class clazz:classes){
            Annotation[] annotations=clazz.getAnnotations();

            for(Annotation annotation:annotations){
                if(annotation instanceof AutoGenerated){
                    System.out.println("AG");
                    autoGeneratedClasses.add(clazz);
                }
            }
           // injectableFields.addAll(scanInjectable(clazz));
        }
        //classAndFields.put(autoGeneratedClasses,injectableFields);
        return autoGeneratedClasses;
    }
    public List<Class<?>> scanControllers(List<Class<?>> classes){
        List<Class<?>> controllerClasses=new ArrayList<>();
        for(Class clazz:classes){
            Annotation[] annotations=clazz.getAnnotations();

            for(Annotation annotation:annotations){
                if(annotation instanceof Controller){
                    System.out.println("Controller");
                    controllerClasses.add(clazz);
                }
            }
        }
        return controllerClasses;
    }

    @Deprecated
    private List<Field> scanInjectable(Class clazz){
        List<Field> injectableFields=new ArrayList<>();
            Field[] fields=clazz.getDeclaredFields();
            for(Field field:fields){
                System.out.println(field.getDeclaringClass()+"/");
                Annotation[] annotations=field.getAnnotations();
                for (Annotation annotation:annotations){
                    if(annotation instanceof Injectable)
                        injectableFields.add(field);
                }
            }
        return injectableFields;
    }


}
