package com.trelloiii.simplereapitinglib.scanner;

import com.trelloiii.simplereapitinglib.AutoGenerated;

import java.lang.annotation.Annotation;
import java.util.ArrayList;
import java.util.List;

public class AnnotationScanner {


    public AnnotationScanner() {
    }

    public List<Class<?>> scanAutoGenerated(List<Class<?>> classes){
        List<Class<?>> autoGeneratedClasses=new ArrayList<>();
        for(Class oneClass:classes){
            Annotation[] annotations=oneClass.getAnnotations();
            for(Annotation annotation:annotations){
                if(annotation instanceof AutoGenerated){
                    System.out.println("AG");
                    autoGeneratedClasses.add(oneClass);
                }
            }
        }
        return autoGeneratedClasses;
    }


}
