package com.trelloiii.simplereapitinglib.scanner;
import com.trelloiii.simplereapitinglib.instance.ObjectInstance;
import com.trelloiii.simplereapitinglib.scanner.test.Person;

import java.io.UnsupportedEncodingException;
import java.util.Arrays;
import java.util.List;

public class Main {
    public static void main(String[] args) throws UnsupportedEncodingException, IllegalAccessException, InstantiationException {
        String pkg="com.trelloiii.simplereapitinglib.scanner.test";
        ClassScanner scanner=ClassScanner.createScanner();
        AnnotationScanner annotationScanner=new AnnotationScanner();
        List<Class<?>> classes= annotationScanner.scanAutoGenerated(scanner.scan(pkg));
        ObjectInstance objectInstance=new ObjectInstance(classes);
    }
}
